# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_comments.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('title', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='reddit_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_comments.RedditPost'),
        ),
    ]
