# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0002_auto_20161229_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='children',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_comments.Comment'),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
