# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0003_auto_20161229_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditpost',
            name='children',
        ),
        migrations.AddField(
            model_name='redditpost',
            name='_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='json_data',
            field=models.TextField(null=True),
        ),
    ]
