# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0004_auto_20161229_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reddit_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_comments.RedditPost'),
        ),
    ]
