# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0005_auto_20161229_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_children', to='app_comments.Comment'),
        ),
    ]
