# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
    ]
