# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0008_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reddit_parent_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
