# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0010_increase'),
    ]

    operations = [
        migrations.AddField(
            model_name='increase',
            name='reddit_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_comments.RedditPost'),
        ),
    ]
